CREATE DATABASE IF NOT EXISTS smarthome_iot;
USE smarthome_iot;

CREATE TABLE IF NOT EXISTS devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  icon VARCHAR(50) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sensor_readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  temperature DECIMAL(5,2) NOT NULL,
  humidity DECIMAL(5,2) NOT NULL,
  device_id VARCHAR(50) NOT NULL,
  recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preferences (
  id INT PRIMARY KEY,
  notifications_enabled TINYINT(1) NOT NULL DEFAULT 0
);
